library(knitr)

#save(baseline_old,file="baseline_old.RData")
#load("baseline_old.RData")
purl('Model Explanatory doc 05_June.Rmd',documentation=0,output='AllEquations_v2.7.R')
source("GenCalib_v2.6.R")
modelLines<-readLines("AllEquations_v2.7.R")
calibrationLines<-readLines("calibration.txt")
indexCalib<-grep("#CALIBRATION",modelLines)
totModel<-c(modelLines[1:(indexCalib-1)],calibrationLines,modelLines[(indexCalib+1):length(modelLines)])
writeLines(totModel,"modelAuto.sfc")
WholeModel<-sfc.model("modelAuto.sfc")
datatest<-simulate(WholeModel)
baseline_new<-as.data.frame(datatest$baseline)
matplot(cbind(baseline_new[1:78,c("yc","yh","yl")],baseline_old[1:78,c("yc","yk","yi")]),type='l',col=1:3,lty=c(1,1,1,2,2,2))
View(cbind(baseline_new[1:200,c("yc","yh","yl")],baseline_old[1:200,c("yc","yk","yi")]))
